### PR TITLE
add mapsApiKey for GeoChart

### PR DESCRIPTION
**Pull request by mikebridge**
The following code works for me in demo mode, but I have some problems importing this into a real project.  Is there someone who wants to try this out before merging it?

Here's an example:

```jsx
// demo/src/App.js
import React from 'react';
import Chart from '../../src/components/Chart';

const options = {
    //displayMode: "markers"
    //displayMode: "text"
};

const data = [
    ["ca", 3],
    ["ru", 4],
    ["us", 5],
    ["gb", 5]
];
const columns = [
    {
        "type": "string",
        "label" : "Country"
    }, {
        "type": "number",
        "label": "Students"
    }];
const App = () => (
  <div className={'my-pretty-chart-container'}>
      <Chart chartType="GeoChart"
             width={"900px"}
             height={"500px"}
             rows={data}
             columns={columns}
             options={options}
             graph_id="GeoChart"
             mapsApiKey="APIKEYHERE"
             legend_toggle={false}/>
  </div>
);
export default App;
```

### CODE REVIEW

**Comment by mikebridge** [comment]
I figured out how to build it and temporarily serve it from github [here](https://github.com/ZeptInc/react-google-charts) so that I could test it out:

```sh
$ yarn add https://github.com/ZeptInc/react-google-charts
```

**Comment by martinratinaud** [comment]
Would be awesome if this could be merged, thanks

**Comment by marcioaffonso** [comment]
Same issue here. The PR needs to be merged.

**Comment by marcioaffonso** [comment]
@RakanNimer would you help us to merge this PR?

**Comment by RakanNimer** [comment]
Thanks for the PR ! 

This will introduce conflicts right now with the PR that adds different language support. 

Going to refactor the chart loader API to make it a bit easier to extends.

Will get back to you here when it's done.

**Comment by adtm** [comment]
Did someone figured out an alternative to this issue or some sort of fix?

**Comment by marcioaffonso** [comment]
@RakanNimer do you know when this will be available? Maybe @mikebridge or myself should publish an alternative version to NPM containing this fix.

**Comment by mikebridge** [comment]
@marcioaffonso Until @RakanNimer refactors the API you can use my forked version by putting this in your package.json's dependencies:

    "react-google-charts": "https://github.com/ZeptInc/react-google-charts"

**Comment by indrajit-rathod** [comment]
@mikebridge your PR is working fine but when I am using a 'select' chart event  sometimes the API key is not getting passed here: https://maps.googleapis.com/maps/api/js?key= and due to that the region is displayed but the markers are not dropped on the regions and the following warning and error is printed in the console.

warning
error

It is happening randomly on page loads also.

Can you help me with this issue ?

**Comment by rakannimer** [comment]
Thanks for the PR !
Should work with 1.6.3 !

**Pull request closed without merging**
