### PR TITLE
Add logic to check if component is unmounted before drawing chart

### LINKED ISSUE #125: Error when container is no more present
Version: 
react-google-charts 1.5.3
react 15.2.1

Expected behaviour
No errors

Actual behaviour
My application render a char in a page. 
If the render is called but I change the page before it is completed, the graph is not yer displayed, 
I get the following error in the console

```
Unhandled rejection Error: The container #reactgooglegraph-1 is not defined.
    at gvjs_Z.gvjs_.getContainer (https://www.gstatic.com/charts/45.1/js/jsapi_compiled_default_module.js:240:313)
    at gvjs_Z.gvjs_.draw (https://www.gstatic.com/charts/45.1/js/jsapi_compiled_default_module.js:236:46)
    at t.drawChart (webpack:///./~/vx-ui-components/lib/index.js?:63:7235)
    at eval (webpack:///./~/vx-ui-components/lib/index.js?:63:3734)
From previous event:
    at t.componentDidMount (webpack:///./~/vx-ui-components/lib/index.js?:63:3716)
    at ReactCompositeComponentWrapper.invokeComponentDidMountWithTimer (webpack:///./~/react/lib/ReactCompositeComponent.js?:54:18)
    at CallbackQueue.notifyAll (webpack:///./~/react/lib/CallbackQueue.js?:67:22)
    at ReactReconcileTransaction.close (webpack:///./~/react/lib/ReactReconcileTransaction.js?:81:26)
    at ReactReconcileTransaction.closeAll (webpack:///./~/react/lib/Transaction.js?:204:25)
    at ReactReconcileTransaction.perform (webpack:///./~/react/lib/Transaction.js?:151:16)
    at ReactUpdatesFlushTransaction.perform (webpack:///./~/react/lib/Transaction.js?:138:20)
    at ReactUpdatesFlushTransaction.perform (webpack:///./~/react/lib/ReactUpdates.js?:90:38)
    at Object.flushBatchedUpdates (webpack:///./~/react/lib/ReactUpdates.js?:173:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (webpack:///./~/react/lib/Transaction.js?:204:25)
    at ReactDefaultBatchingStrategyTransaction.perform (webpack:///./~/react/lib/Transaction.js?:151:16)
    at Object.batchedUpdates (webpack:///./~/react/lib/ReactDefaultBatchingStrategy.js?:63:19)
    at Object.enqueueUpdate (webpack:///./~/react/lib/ReactUpdates.js?:201:22)
    at enqueueUpdate (webpack:///./~/react/lib/ReactUpdateQueue.js?:25:16)
    at Object.enqueueSetState (webpack:///./~/react/lib/ReactUpdateQueue.js?:209:5)
    at Connect.ReactComponent.setState (webpack:///./~/react/lib/ReactComponent.js?:64:16)
    at Connect.handleChange (webpack:///./~/react-redux/lib/components/connect.js?:301:14)
    at Object.dispatch (webpack:///./~/redux/lib/createStore.js?:186:19)
    at dispatch (<anonymous>:2:31397)

```
Moreover...
If the render completely executed and I change the page after it is completed, once I've changed the page, everytime I resize the windows
I get the following error in the console

```
Uncaught Error: google-visualization-errors: container is null
    at Object.gvjs_T.Kc (jsapi_compiled_default_module.js:103)
    at t.updateDataTable (index.js:63)
    at t.drawChart (index.js:63)
    at t.onResize (index.js:63)
```

Here my code:
```
render() {
    
      return (<Chart
        chartType={this.props.type}
        data={this.props.data}
        options={this.props.options}
        graph_id={this.props.uuid}
        width={this.props.dimensions.width}
        height={this.props.dimensions.height}
        chartPackage= {['controls']}
        chartEvents={this.state.chart_events}
        ref={(ref) => this.GoogleChart = ref}
      />);
  }
```
I tried with and without the graph_id.

Steps to reproduce
I can easily reproduce in my app. I do not have yet a example you can play with but I could share with you my desktop.

Link to a git repo that reproduces bug : 
No

Question:
How I can avoid this behaviour? Is there a way to fix this issue?

P.S. Please do not close the issue... leave it open so we can discuss over it.

### PR DESCRIPTION
**Pull request by youngzhaosignifyd**
This resolves #125

### CODE REVIEW

**Comment by RakanNimer** [comment]
Thanks for submitting the PR ! 

Shouldn't we also set isUnmounted to false on componentWillMount ?

**Comment by youngzhaosignifyd** [comment]
You are welcome!

Setting `isUnmounted` to `false` is not needed because `isUnmounted` is undefined until `componentWillUnmount` is called.

I can add a `this.isUnmounted = false` if you prefer to declare all the member variables by default. But is `constructor` a better place?

**Comment by gberth** [comment]
Hi. Is there any reason why this is not merged? Or is it? I seem to get similiar problems drawing three graphs with the same component (three times) in the same window. Only the last one appears and the two others give some promise error.

**Comment by gberth** [comment]
Updating the code with suggested merge fixes the exception, but I only get one of the graphs drawn. Suppose this has to do with my lack of competence with react, but if someone would give ma a hint on how to draw three different charts on the same page, with the same component, I would be very glad :-)

**Comment by kjellski** [comment]
*bump* Is there a reason this is not merged? Can someone jump in and help somehow? 
/cc @RakanNimer @youngzhaosignifyd

**Comment by youngzhaosignifyd** [comment]
I don't have the authorization to merge. 

@kjellski @gberth What kind of help do you need? Can you be more specific?

**Comment by kjellski** [comment]
@youngzhaosignifyd the question was more directed towards @RakanNimer. I think he's currently the only one that would merge it, right? I thought that maybe something is missing and I could help to provide it. Other then that, I don't know why it shouldn't be merged ;)

**Comment by youngzhaosignifyd** [comment]
@kjellski - yes. I am not the owner so I can't merge. 

My workaround is to set loadCharts to false, and implement the logic to load google charts myself:

```
import googleChartsLoader from './googleChartsLoader';

class MyChart extends React.Component {
  constructor(props) {
    this.super(props);
    this.state = {
      loading: true,
      key: 1
    };
  }

  redrawChart() {
    this.setState({
      key: this.key + 1
    })
  }

  componentDidMount() {
    this.isUmmounted = false;
    
    googleChartsLoader().then(() => {
      // if component is going to be unmounted, no need to render chart
      if (!this.isUmmounted) this.props.setLoading(false);
    });

    window.addEventListener('resize', this.redrawChart);
  }

  componentWillUnmount() {
    this.isUmmounted = true;
    window.removeEventListener('resize', this.redrawChart);
  }

  render() {
    if (this.state.loading) return null;

    return (
      <Chart
        key={this.state.key}
        {...this.props.chartProps}
        loader=" "
        loadCharts={false}
      />
    );
  }
}
```

```
import loadjs from 'loadjs';

let promise;

// Load google charts js here and disable loadCharts on react-google-charts
// This is to fix the "The container #reactgooglegraph-1 is not defined" bug when
// unmount the google chart component BEFORE the google charts js is loaded
// REF: https://github.com/RakanNimer/react-google-charts/issues/125
export default function googleChartsLoader(): Promise<*> {
  // Load Google Charts loader.js can only once
  if (promise) return promise;

  promise = new Promise((resolve, reject) => {
    loadjs('https://www.gstatic.com/charts/loader.js', {
      success: () => {
        window.google.charts.load('current', { packages: ['corechart'] });
        window.google.charts.setOnLoadCallback(() => resolve());
      },
      error: () => {
        reject();
      }
    });
  });

  return promise;
}
```

**Comment by Joeper214** [comment]
Is this available in the latest version tag?

**Pull request merged**
