### PR TITLE
Added support for window.resize with lodash debounce

### PR DESCRIPTION
**Pull request by mkontula**
Added support for responsive charts based on: http://stackoverflow.com/questions/23123138/perform-debounce-in-react-js/28046731#2804673.

### CODE REVIEW

**Comment by vaclav-zeman** [comment]
Responsiveness is the only thing I miss about this library. This is great.

**Comment by RakanNimer** [comment]
Hey @mkontula ,
Thanks for this ! I'm hesitant to add another dependency to the project (lodash) at this stage especially since the logic added can be used without modifying the Chart.js code.
I'll leave this pull request open to gauge interest for this feature.
Cheers !

**Comment by russelldc** [comment]
How could this be accomplished without modifying the library?

**Comment by rickyPanzer** [comment]
+1 this feature

**Comment by cfitton** [comment]
+1 this feature

**Comment by RakanNimer** [comment]
Hey thanks @mkontula  for this PR, I'm closing it in favor of #98 .
Cheers !

**Pull request closed without merging**
